---
services:
  discord-rss-bot:
    image: ghcr.io/violetcranberry/discord-rss-bot:latest
    container_name: discord-rss-bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    restart: unless-stopped
  # command:
  #   - "--token=${DISCORD_BOT_TOKEN}"
  #   - "--debug"
