name: Pylint check
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==2.0.1
          poetry install --with dev
      - name: Lint with pylint
        run: |
          poetry run pylint --verbose --output-format=text discord_rss_bot | tee pylint_output.log
      - name: Generate badge
        run: |
          mkdir -p ./.github/badges
          SCORE=$(grep "Your code has been rated at" pylint_output.log \
            | awk '{print $7}' | cut -d/ -f1)
          poetry run anybadge \
          --file=./.github/badges/pylint.svg \
          --label='pyint score' --overwrite \
          --value=$SCORE 2=red 4=orange 8=yellow 9=green
          echo "PyLint Score: $SCORE"
      - name: Commit badge to repo
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./.github/badges/pylint.svg
          # Check for changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update Pylint badge [skip ci]"
          git pull --rebase
          git push
